services:
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    ports:
      - 4173:4173
    env_file:
      - .env
  backend:
    build:
      context: ./backend
    ports:
      - 7070:7070
    env_file:
      - .env
    shm_size: '256mb'
    volumes:
      - ./database:/app/database
      - ./submissions:/app/submissions

volumes:
  database_data:
    driver: local